// Generated by CoffeeScript 1.8.0
(function() {
  var DialplanFunction, FunctionList, append, functions, name;

  FunctionList = require('./function.json');

  functions = {};

  DialplanFunction = function(name, attrs) {
    var attrsAsString;
    attrsAsString = attrs.join(',');
    return "" + name + "(" + attrsAsString + ")";
  };

  append = function(name) {
    return functions[name] = function() {
      var args;
      args = [].slice.call(arguments, 0);
      return DialplanFunction(name, args);
    };
  };

  for (name in FunctionList) {
    append(name);
  }

  module.exports = functions;

}).call(this);
