// Generated by CoffeeScript 1.8.0
(function() {
  var Expression, Global, Value;

  Value = function(str) {
    return "${" + str + "}";
  };

  Expression = function() {
    var args;
    args = [].slice.call(arguments, 0);
    if (args.length !== 3) {
      throw new Error('Check count args');
    }
    return '$[' + args[0] + args[1] + args[2] + ']';
  };

  Global = function(str) {
    return "__" + str;
  };

  module.exports = {
    $: Value,
    Expression: Expression,
    Global: Global
  };

}).call(this);
